default:
  image: node:17.2.0
  before_script:
    - yarn install

stages:
  - build

build-app:
  stage: build
  script:
    - echo "Building app..."
    - yarn build
    - apt update
    - apt -y install zip unzip
    - zip -r build-$CI_PIPELINE_ID.zip build
    - echo "Done!"
  artifacts:
    paths:
      - build-$CI_PIPELINE_ID.zip